# there is no reason to use this makefile manually

.PHONY: build clean

ifeq (,$(PLATFORM))
$(error please specify PLATFORM, eg. make PLATFORM=tg5040)
endif

.EXPORT_ALL_VARIABLES:
# pseudo toolchain
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Linux)
	CROSS_COMPILE=/usr/bin/
	PREFIX=/usr
endif
ifeq ($(UNAME_S),Darwin)
	# Run ./workspace/desktop/macos_create_gcc_symlinks.sh once after `brew install gcc`.
	# It creates only repo-local wrappers; no sudo or /usr/local/bin mutation is needed.
	GCC_WRAPPERS=$(CURDIR)/workspace/desktop/.toolchain
	PATH:=$(GCC_WRAPPERS):$(PATH)
	CROSS_COMPILE=$(GCC_WRAPPERS)/
	PREFIX=/opt/homebrew
endif
PREFIX_LOCAL=/var/tmp/nextui
UNION_PLATFORM=desktop

all: 
	
clean:
	cd workspace && $(MAKE) clean
	
build: 
	cd workspace && COMPILE_CORES=$(COMPILE_CORES) $(MAKE)

build-cores: 
	cd workspace && COMPILE_CORES=true $(MAKE) cores

build-core:
ifndef CORE
	$(error CORE is not set)
endif
	cd workspace && COMPILE_CORES=true CORE=$(CORE) $(MAKE) core
