# h700
OPT = -O3 -Ofast -fomit-frame-pointer
# -mtune/-march/-mpcu
# "When porting from x86 to Arm, you should replace any occurrences of -march 
# with -mcpu and remove any instances of -mtune.  
# This will have the desired effect of simultaneously tuning for the target 
# architecture and microarchitecture."
# https://developer.arm.com/community/arm-community-blogs/b/tools-software-ides-blog/posts/compiler-flags-across-architectures-march-mtune-and-mcpu
CFLAGS = -mcpu=cortex-a53 -flto
SDL = SDL2
GL = GLES
# legacy linux paths
CFLAGS += -I$(PREFIX_LOCAL)/include -I$(PREFIX)/include
LDFLAGS = -L$(PREFIX_LOCAL)/lib -L$(PREFIX)/lib
# multiarch support
CFLAGS += -I$(PREFIX)/include/$(CROSS_TRIPLE)
LDFLAGS += -L$(PREFIX_LOCAL)/lib/$(CROSS_TRIPLE) -L$(PREFIX)/lib/$(CROSS_TRIPLE)
# pkg-config
export PKG_CONFIG_PATH := $(PREFIX_LOCAL)/lib/pkgconfig:$(PREFIX_LOCAL)/lib/$(CROSS_TRIPLE)/pkgconfig:$(PKG_CONFIG_PATH)
CFLAGS += $$(pkg-config --cflags sdl2 glesv2)
# The inherited TrimUI glesv2.pc links libUMP, which H700's graphics stack does not use.
# Link GLESv2 directly until the toolchain provides H700-specific pkg-config metadata.
LDFLAGS += $$(pkg-config --libs sdl2) -lGLESv2
# not handled by pkg-config
CFLAGS += -DUSE_$(SDL) -DUSE_$(GL) -DGL_GLEXT_PROTOTYPES
LDFLAGS += -l$(SDL)_image -l$(SDL)_ttf -lpthread -ldl -lm -lz
