# desktop
# In CI, disable debug symbols to avoid dsymutil memory issues on macOS
ifdef CI
OPT =
else
OPT = -g
endif
CFLAGS = -flto=auto -Wall -Wextra -Wformat=2 -DHTTP_USE_SYSTEM_CA
SDL = SDL2
GL = GL

# legacy linux paths
CFLAGS += -I$(PREFIX)/include -I$(PREFIX_LOCAL)/include
LDFLAGS = -L$(PREFIX)/lib -L$(PREFIX_LOCAL)/lib

# dependencies
CFLAGS += -DUSE_$(SDL)
LDFLAGS += -lpthread -ldl -lm -lz

# platform dependencies
ifeq ($(UNAME_S),Linux)
    # pkg-config
    CFLAGS += `pkg-config --cflags sdl2 SDL2_image SDL2_ttf`
    LDFLAGS += `pkg-config --libs sdl2 SDL2_image SDL2_ttf`
    # opengl
    CFLAGS += -DUSE_$(GL) -DGL_GLEXT_PROTOTYPES
    LDFLAGS += -lGL
endif

ifeq ($(UNAME_S),Darwin)
    # sdl
    LDFLAGS += -l$(SDL) -l$(SDL)_image -l$(SDL)_ttf
    # opengl
    CFLAGS += -DUSE_$(GL) -DGL_GLEXT_PROTOTYPES
    LDFLAGS += -framework OpenGL
    # sqlite
    CFLAGS += -I/opt/homebrew/opt/sqlite/include
    LDFLAGS += -L/opt/homebrew/opt/sqlite/lib
endif

# we have some super old opengl code that throws warnings a lot
CFLAGS += -DGL_SILENCE_DEPRECATION
# TODO: this shouldnt be necessary.
# move resampling code out of api.c
LDFLAGS += -lsamplerate