#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <errno.h>
#include <limits.h>
#include <sys/stat.h>
#include <unistd.h>
#include <zip.h>

#include "archive_extract.h"

#include "ma_internal.h"
#include "ma_game.h"

struct Game game;
struct retro_disk_control_ext_callback disk_control_ext;

static void remove_extracted_game(void) {
	if (!game.tmp_path[0]) return;
	char *slash = strrchr(game.tmp_path, '/');
	unlink(game.tmp_path);
	if (slash) {
		*slash = '\0';
		rmdir(game.tmp_path);
	}
	game.tmp_path[0] = '\0';
}

void Game_open(char* path) {
	LOG_info("Game_open\n");
	memset(&game, 0, sizeof(game));

	if (!path || strlen(path) >= sizeof(game.path)) {
		LOG_error("Game path is too long\n");
		return;
	}
	strcpy((char*)game.path, path);
	char *filename = strrchr(path, '/');
	if (!filename || !filename[1] || strlen(filename + 1) >= sizeof(game.name)) {
		LOG_error("Game path has no filename\n");
		return;
	}
	strcpy((char*)game.name, filename + 1);
	strcpy((char*)game.alt_name, game.name); // default it

	// if we have a zip file
	if (suffixMatch(".zip", game.path)) {
		LOG_info("is zip file\n");
		int supports_zip = 0;
		int i = 0;
		char* ext;
		char exts[128];
		char* extensions[32];
		strcpy(exts,core.extensions);
		while ((ext=strtok(i?NULL:exts,"|"))) {
			extensions[i++] = ext;
			if (!strcmp("zip", ext)) {
				supports_zip = 1;
				break;
			}
		}
		extensions[i] = NULL;

		// if the core doesn't support zip files natively
		if (!supports_zip) {
			// extract zip file located at game.path to game.tmp_path
			// game.tmp_path is temp dir generated by mkdtemp
			LOG_info("Extracting zip file manually: %s\n", game.path);
			if(!extract_zip(extensions))
				return;
			// Update the game name to the extracted file name instead of the zip name
			if (CFG_getUseExtractedFileName())
				strcpy((char*)game.alt_name, strrchr(game.tmp_path, '/')+1);
		}
		else {
			LOG_info("Core can handle zip file: %s\n", game.path);
		}
	}

	// some cores handle opening files themselves, eg. pcsx_rearmed
	// if the frontend tries to load a 500MB file itself bad things happen
	if (!core.need_fullpath) {
		path = game.tmp_path[0]=='\0'?game.path:game.tmp_path;

		FILE *file = fopen(path, "r");
		if (file==NULL) {
			LOG_error("Error opening game: %s\n\t%s\n", path, strerror(errno));
			remove_extracted_game();
			return;
		}

		fseek(file, 0, SEEK_END);
		game.size = ftell(file);

		rewind(file);
		game.data = malloc(game.size);
		if (game.data==NULL) {
			LOG_error("Couldn't allocate memory for file: %s\n", path);
			fclose(file);
			remove_extracted_game();
			return;
		}

		fread(game.data, sizeof(uint8_t), game.size, file);

		fclose(file);
	}

	// m3u-based?
	char* tmp;
	char m3u_path[256];
	char base_path[256];
	char dir_name[256];

	strcpy(m3u_path, game.path);
	tmp = strrchr(m3u_path, '/') + 1;
	tmp[0] = '\0';

	strcpy(base_path, m3u_path);

	tmp = strrchr(m3u_path, '/');
	tmp[0] = '\0';

	tmp = strrchr(m3u_path, '/');
	strcpy(dir_name, tmp);

	tmp = m3u_path + strlen(m3u_path);
	strcpy(tmp, dir_name);

	tmp = m3u_path + strlen(m3u_path);
	strcpy(tmp, ".m3u");

	if (exists(m3u_path)) {
		strcpy(game.m3u_path, m3u_path);
		strcpy((char*)game.name, strrchr(m3u_path, '/')+1);
		strcpy((char*)game.alt_name, game.name); // default it
	}

	game.is_open = 1;
}

void Game_close(void) {
	free(game.data);
	game.data = NULL;
	game.size = 0;
	remove_extracted_game();
	game.is_open = 0;
	VIB_setStrength(0); // just in case
}

void Game_changeDisc(char* path) {

	if (exactMatch(game.path, path) || !exists(path)) return;

	Game_close();
	Game_open(path);

	struct retro_game_info game_info = {};
	game_info.path = game.path;
	game_info.data = game.data;
	game_info.size = game.size;

	disk_control_ext.replace_image_index(0, &game_info);
	putFile(CHANGE_DISC_PATH, path); // NextUI still needs to know this to update recents.txt
}

int extract_zip(char** extensions)
{
	char buf[4096];
	char tmp_dir[MAX_PATH];
	char member_name[MAX_PATH];
	struct zip *za;
	int ze;
	int success = 0;

	if ((za = zip_open(game.path, 0, &ze)) == NULL) {
		zip_error_t error;
		zip_error_init_with_code(&error, ze);
		LOG_error("can't open zip archive `%s': %s\n", game.path, zip_error_strerror(&error));
		return 0;
	}
	if (archive_make_private_dir(tmp_dir, sizeof(tmp_dir)) != 0) {
		LOG_error("can't create private extraction directory: %s\n", strerror(errno));
		zip_close(za);
		return 0;
	}

	for (zip_int64_t i = 0; i < zip_get_num_entries(za, 0); i++) {
		struct zip_stat sb;
		const char *extension;
		int found = 0;
		int fd = -1;
		struct zip_file *zf;
		zip_int64_t total = 0;

		if (zip_stat_index(za, i, 0, &sb) != 0) continue;
		if (sb.name && sb.name[0] && sb.name[strlen(sb.name) - 1] == '/') continue;
		if (!sb.name || !sb.name[0] || sb.size > LLONG_MAX ||
			archive_member_basename(sb.name, member_name, sizeof(member_name)) != 0) {
			LOG_error("unsafe zip member name\n");
			goto done;
		}
		extension = strrchr(member_name, '.');
		if (!extension || !extension[1]) continue;
		for (int e = 0; extensions[e]; e++) {
			if (strcasecmp(extension + 1, extensions[e]) == 0) {
				found = 1;
				break;
			}
		}
		if (!found) continue;
		if (snprintf(game.tmp_path, sizeof(game.tmp_path), "%s/%s", tmp_dir, member_name) >= (int)sizeof(game.tmp_path)) {
			LOG_error("extracted path is too long\n");
			goto done;
		}

		zf = zip_fopen_index(za, i, 0);
		if (!zf) {
			LOG_error("zip_fopen_index failed\n");
			goto done;
		}
		int open_result = archive_open_output(tmp_dir, member_name, (off_t)sb.size, &fd);
		if (open_result < 0) {
			LOG_error("can't safely create extracted file: %s\n", strerror(errno));
			zip_fclose(zf);
			goto done;
		}
		if (open_result == 1) {
			zip_fclose(zf);
			success = 1;
			break;
		}

		while (total < (zip_int64_t)sb.size) {
			zip_uint64_t remaining = sb.size - (zip_uint64_t)total;
			zip_uint64_t want = remaining < sizeof(buf) ? remaining : sizeof(buf);
			zip_int64_t read = zip_fread(zf, buf, want);
			if (read <= 0 || archive_write_all(fd, buf, (size_t)read) != 0) {
				LOG_error("failed extracting zip member\n");
				close(fd);
				unlink(game.tmp_path);
				zip_fclose(zf);
				goto done;
			}
			total += read;
		}
		if (close(fd) != 0) {
			unlink(game.tmp_path);
			zip_fclose(zf);
			goto done;
		}
		zip_fclose(zf);
		success = 1;
		break;
	}

done:
	if (zip_close(za) == -1) {
		LOG_error("can't close zip archive `%s'\n", game.path);
		success = 0;
	}
	if (!success) {
		if (game.tmp_path[0]) unlink(game.tmp_path);
		game.tmp_path[0] = '\0';
		rmdir(tmp_dir);
	}
	return success;
}
